"""add user_id to waste_generators

Revision ID: 22b6a07e6399
Revises: 62f0d6587174
Create Date: 2026-09-13 00:45:45.329799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b6a07e6399'
down_revision: Union[str, None] = '62f0d6587174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_generators', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_waste_generators_user_id'), 'waste_generators', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_waste_generators_user_id_users'), 'waste_generators', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_waste_generators_user_id_users'), 'waste_generators', type_='foreignkey')
    op.drop_index(op.f('ix_waste_generators_user_id'), table_name='waste_generators')
    op.drop_column('waste_generators', 'user_id')
    # ### end Alembic commands ###
