"""add user_id to facilities

Revision ID: 62f0d6587174
Revises: bd530580d82b
Create Date: 2026-09-12 21:03:39.514720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f0d6587174'
down_revision: Union[str, None] = 'bd530580d82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_facilities_user_id'), 'facilities', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_facilities_user_id_users'), 'facilities', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_facilities_user_id_users'), 'facilities', type_='foreignkey')
    op.drop_index(op.f('ix_facilities_user_id'), table_name='facilities')
    op.drop_column('facilities', 'user_id')
    # ### end Alembic commands ###
