"""initial schema

Revision ID: b87ef22d4542
Revises: 3dce37b6e80c
Create Date: 2026-09-12 10:43:07.748330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 - required for the Geography column type below;
                     # Alembic's autogenerate detects GeoAlchemy2 types but does not
                     # emit this import on its own (a known geoalchemy2 gotcha).


# revision identifiers, used by Alembic.
revision: str = 'b87ef22d4542'
down_revision: Union[str, None] = '3dce37b6e80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_type', sa.Enum('BIOCHAR', 'BIOGAS', 'BIOMASS_CONVERSION', name='facility_type'), nullable=False),
    sa.Column('capacity_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_load_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accepted_waste_types', sa.ARRAY(sa.Enum('RICE_STRAW', 'WHEAT_STRAW', 'COTTON_RESIDUE', 'SUGARCANE_RESIDUE', 'FOOD_WASTE', 'ORGANIC_WASTE', 'ANIMAL_MANURE', name='waste_type')), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='facility_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    # NOTE: no explicit create_index for 'location' here - GeoAlchemy2 attaches
    # a DDL event to Geography columns that creates the GIST spatial index
    # automatically on create_table(). Autogenerate doesn't know that and will
    # propose a duplicate; the duplicate call is removed by hand in every
    # migration that adds a geography column (see the geoalchemy2 FAQ).
    op.create_index(op.f('ix_facilities_facility_type'), 'facilities', ['facility_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'WASTE_GENERATOR', 'FACILITY_OPERATOR', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('waste_generators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generator_type', sa.Enum('FARM', 'FOOD_INDUSTRY', 'MUNICIPALITY', 'INDUSTRIAL', name='generator_type'), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_generators'))
    )
    # (GeoAlchemy2 auto-creates the 'location' GIST index - see note above)
    op.create_index(op.f('ix_waste_generators_generator_type'), 'waste_generators', ['generator_type'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generator_id', sa.UUID(), nullable=False),
    sa.Column('waste_type', sa.Enum('RICE_STRAW', 'WHEAT_STRAW', 'COTTON_RESIDUE', 'SUGARCANE_RESIDUE', 'FOOD_WASTE', 'ORGANIC_WASTE', 'ANIMAL_MANURE', name='waste_type'), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_quantity_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['waste_generators.id'], name=op.f('fk_forecasts_generator_id_waste_generators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts'))
    )
    op.create_index(op.f('ix_forecasts_generator_id'), 'forecasts', ['generator_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_capacity_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimated_transport_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_waste_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('route_geometry', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', name='route_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_routes_facility_id_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    # (GeoAlchemy2 auto-creates the 'route_geometry' GIST index - see note above)
    op.create_index(op.f('ix_routes_facility_id'), 'routes', ['facility_id'], unique=False)
    op.create_table('waste_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generator_id', sa.UUID(), nullable=False),
    sa.Column('waste_type', sa.Enum('RICE_STRAW', 'WHEAT_STRAW', 'COTTON_RESIDUE', 'SUGARCANE_RESIDUE', 'FOOD_WASTE', 'ORGANIC_WASTE', 'ANIMAL_MANURE', name='waste_type'), nullable=False),
    sa.Column('quantity_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moisture_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('available_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'PENDING', 'COLLECTED', 'PROCESSED', name='waste_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['waste_generators.id'], name=op.f('fk_waste_records_generator_id_waste_generators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_records'))
    )
    op.create_index(op.f('ix_waste_records_generator_id'), 'waste_records', ['generator_id'], unique=False)
    op.create_index(op.f('ix_waste_records_status'), 'waste_records', ['status'], unique=False)
    op.create_index(op.f('ix_waste_records_waste_type'), 'waste_records', ['waste_type'], unique=False)
    op.create_table('carbon_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waste_record_id', sa.UUID(), nullable=False),
    sa.Column('waste_quantity_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conversion_type', sa.Enum('BIOCHAR', 'BIOGAS', 'BIOMASS_CONVERSION', name='facility_type'), nullable=False),
    sa.Column('conversion_output_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carbon_content_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_sequestered_co2_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transport_emissions_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_co2_impact_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('methodology_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['waste_record_id'], ['waste_records.id'], name=op.f('fk_carbon_records_waste_record_id_waste_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carbon_records'))
    )
    op.create_index(op.f('ix_carbon_records_waste_record_id'), 'carbon_records', ['waste_record_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waste_record_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimated_transport_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reasons', sa.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('status', sa.Enum('RECOMMENDED', 'ACCEPTED', 'REJECTED', name='match_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_matches_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_record_id'], ['waste_records.id'], name=op.f('fk_matches_waste_record_id_waste_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_facility_id'), 'matches', ['facility_id'], unique=False)
    op.create_index(op.f('ix_matches_waste_record_id'), 'matches', ['waste_record_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('waste_record_id', sa.UUID(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('quantity_tonnes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_stops_route_id_routes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_record_id'], ['waste_records.id'], name=op.f('fk_route_stops_waste_record_id_waste_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops'))
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_matches_waste_record_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_facility_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_carbon_records_waste_record_id'), table_name='carbon_records')
    op.drop_table('carbon_records')
    op.drop_index(op.f('ix_waste_records_waste_type'), table_name='waste_records')
    op.drop_index(op.f('ix_waste_records_status'), table_name='waste_records')
    op.drop_index(op.f('ix_waste_records_generator_id'), table_name='waste_records')
    op.drop_table('waste_records')
    op.drop_index(op.f('ix_routes_facility_id'), table_name='routes')
    op.drop_table('routes')  # drop_table also removes GeoAlchemy2's auto-created spatial index
    op.drop_index(op.f('ix_forecasts_generator_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_waste_generators_generator_type'), table_name='waste_generators')
    op.drop_table('waste_generators')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_facilities_facility_type'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
