"""add facility_id to carbon_records

Revision ID: bd530580d82b
Revises: b87ef22d4542
Create Date: 2026-09-12 12:49:28.716177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd530580d82b'
down_revision: Union[str, None] = 'b87ef22d4542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carbon_records', sa.Column('facility_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_carbon_records_facility_id'), 'carbon_records', ['facility_id'], unique=False)
    op.create_foreign_key(op.f('fk_carbon_records_facility_id_facilities'), 'carbon_records', 'facilities', ['facility_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_carbon_records_facility_id_facilities'), 'carbon_records', type_='foreignkey')
    op.drop_index(op.f('ix_carbon_records_facility_id'), table_name='carbon_records')
    op.drop_column('carbon_records', 'facility_id')
    # ### end Alembic commands ###
